package com.example.domain

data class Quote(
    val id: Int,
    val text: String,
    val author: String
)

object QuotesRepository {
    val quotes: List<Quote> = listOf(
        Quote(1, "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "Aristotle"),
        Quote(2, "Small disciplines repeated with consistency every day lead to great achievements.", "John C. Maxwell"),
        Quote(3, "You do not rise to the level of your goals. You fall to the level of your systems.", "James Clear"),
        Quote(4, "Waste no more time arguing about what a good man should be. Be one.", "Marcus Aurelius"),
        Quote(5, "It is not that we have a short time to live, but that we waste a lot of it.", "Seneca"),
        Quote(6, "The secret of getting ahead is getting started.", "Mark Twain"),
        Quote(7, "First say to yourself what you would be; and then do what you have to do.", "Epictetus"),
        Quote(8, "A journey of a thousand miles begins with a single step.", "Lao Tzu"),
        Quote(9, "Energy and persistence conquer all things.", "Benjamin Franklin"),
        Quote(10, "Motivation is what gets you started. Habit is what keeps you going.", "Jim Ryun"),
        Quote(11, "Continuous effort—not strength or intelligence—is the key to unlocking our potential.", "Winston Churchill"),
        Quote(12, "Do what you can, with what you have, where you are.", "Theodore Roosevelt"),
        Quote(13, "Action is the foundational key to all success.", "Pablo Picasso"),
        Quote(14, "Discipline is the bridge between goals and accomplishment.", "Jim Rohn"),
        Quote(15, "In the middle of difficulty lies opportunity.", "Albert Einstein"),
        Quote(16, "What we achieve inwardly will change outer reality.", "Plutarch"),
        Quote(17, "Success is the sum of small efforts, repeated day in and day out.", "Robert Collier"),
        Quote(18, "He who has a why to live can bear almost any how.", "Friedrich Nietzsche"),
        Quote(19, "The impediment to action advances action. What stands in the way becomes the way.", "Marcus Aurelius"),
        Quote(20, "Doubt is only removed by action. If you're not working then that's where doubt comes in.", "Conor McGregor"),
        Quote(21, "Never leave that till tomorrow which you can do today.", "Benjamin Franklin"),
        Quote(22, "Simplicity is the ultimate sophistication.", "Leonardo da Vinci"),
        Quote(23, "An ounce of practice is generally worth more than a ton of theory.", "E.F. Schumacher"),
        Quote(24, "Difficulties strengthen the mind, as labor does the body.", "Seneca"),
        Quote(25, "The only bad workout is the one that didn't happen.", "Unknown"),
        Quote(26, "Consistency is the DNA of mastery.", "Robin Sharma"),
        Quote(27, "Little by little, one walks far.", "Peruvian Proverb"),
        Quote(28, "The habit of persistence is the habit of victory.", "Herbert Kaufman"),
        Quote(29, "To improve is to change; to be perfect is to change often.", "Winston Churchill"),
        Quote(30, "The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"),
        Quote(31, "Nothing will work unless you do.", "Maya Angelou"),
        Quote(32, "Patience, persistence and perspiration make an unbeatable combination for success.", "Napoleon Hill"),
        Quote(33, "Your daily life is your temple and your religion.", "Kahlil Gibran"),
        Quote(34, "He who conquers himself is the mightiest warrior.", "Confucius"),
        Quote(35, "Day by day, what you choose, what you think and what you do is who you become.", "Heraclitus"),
        Quote(36, "Do not pray for an easy life, pray for the strength to endure a difficult one.", "Bruce Lee"),
        Quote(37, "If you want to fly, you have to give up the things that weigh you down.", "Toni Morrison"),
        Quote(38, "Character is simply habit long continued.", "Plutarch"),
        Quote(39, "Live as if you were to die tomorrow. Learn as if you were to live forever.", "Mahatma Gandhi"),
        Quote(40, "Great things are done by a series of small things brought together.", "Vincent van Gogh"),
        Quote(41, "Self-command is the greatest of all reigns.", "Seneca"),
        Quote(42, "Focus on the step in front of you, not the whole staircase.", "Unknown"),
        Quote(43, "Iron rusts from disuse; water loses its purity from stagnation... even so does inaction sap the vigors of the mind.", "Leonardo da Vinci"),
        Quote(44, "The mind is everything. What you think you become.", "Buddha"),
        Quote(45, "No man is free who cannot command himself.", "Pythagoras"),
        Quote(46, "It always seems impossible until it's done.", "Nelson Mandela"),
        Quote(47, "Make each day your masterpiece.", "John Wooden"),
        Quote(48, "You cannot change your destination overnight, but you can change your direction overnight.", "Jim Rohn"),
        Quote(49, "The soul becomes dyed with the color of its thoughts.", "Marcus Aurelius"),
        Quote(50, "Only those who dare to fail greatly can ever achieve greatly.", "Robert F. Kennedy"),
        Quote(51, "Courage is not having the strength to go on; it is going on when you don't have the strength.", "Theodore Roosevelt"),
        Quote(52, "Success is nothing more than a few simple disciplines, practiced every day.", "Jim Rohn"),
        Quote(53, "Well done is better than well said.", "Benjamin Franklin"),
        Quote(54, "Don't count the days, make the days count.", "Muhammad Ali"),
        Quote(55, "There are no shortcuts to any place worth going.", "Beverly Sills"),
        Quote(56, "Do one thing every day that scares you.", "Eleanor Roosevelt"),
        Quote(57, "If you are going through hell, keep going.", "Winston Churchill"),
        Quote(58, "Mastering others is strength. Mastering yourself is true power.", "Lao Tzu"),
        Quote(59, "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", "Socrates"),
        Quote(60, "The way to get started is to quit talking and begin doing.", "Walt Disney"),
        Quote(61, "Perseverance is failing 19 times and succeeding the 20th.", "Julie Andrews"),
        Quote(62, "Quality is not an act, it is a habit.", "Aristotle"),
        Quote(63, "Start where you are. Use what you have. Do what you can.", "Arthur Ashe"),
        Quote(64, "A champion is defined not by their wins but by how they can recover when they fall.", "Serena Williams"),
        Quote(65, "Happiness is not something ready made. It comes from your own actions.", "Dalai Lama"),
        Quote(66, "Everything you've ever wanted is on the other side of fear.", "George Addair"),
        Quote(67, "Do not wait; the time will never be 'just right.'", "Napoleon Hill"),
        Quote(68, "Strength does not come from physical capacity. It comes from an indomitable will.", "Mahatma Gandhi"),
        Quote(69, "The man who moves a mountain begins by carrying away small stones.", "Confucius"),
        Quote(70, "Believe you can and you're halfway there.", "Theodore Roosevelt"),
        Quote(71, "It is our choices that show what we truly are, far more than our abilities.", "J.K. Rowling"),
        Quote(72, "Today is victory over yourself of yesterday; tomorrow is your victory over lesser men.", "Miyamoto Musashi"),
        Quote(73, "Drop by drop is the water pot filled.", "Buddha"),
        Quote(74, "Victory belongs to the most persevering.", "Napoleon Bonaparte"),
        Quote(75, "What gets measured gets managed.", "Peter Drucker"),
        Quote(76, "It does not matter how slowly you go as long as you do not stop.", "Confucius"),
        Quote(77, "The difference between ordinary and extraordinary is that little extra.", "Jimmy Johnson"),
        Quote(78, "Either you run the day or the day runs you.", "Jim Rohn"),
        Quote(79, "Stay committed to your decisions, but stay flexible in your approach.", "Tony Robbins"),
        Quote(80, "Action may not always bring happiness, but there is no happiness without action.", "William James"),
        Quote(81, "Fortune favors the bold.", "Virgil"),
        Quote(82, "You miss 100% of the shots you don't take.", "Wayne Gretzky"),
        Quote(83, "A year from now you may wish you had started today.", "Karen Lamb"),
        Quote(84, "The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"),
        Quote(85, "If you want something you've never had, you must be willing to do something you've never done.", "Thomas Jefferson"),
        Quote(86, "Do what is right, not what is easy nor what is popular.", "Roy T. Bennett"),
        Quote(87, "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.", "Earl Nightingale"),
        Quote(88, "You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"),
        Quote(89, "Your habits will determine your future.", "Jack Canfield"),
        Quote(90, "Discipline equals freedom.", "Jocko Willink"),
        Quote(91, "Rome was not built in a day, but they were laying bricks every hour.", "John Heywood"),
        Quote(92, "An unexamined life is not worth living.", "Socrates"),
        Quote(93, "In any moment of decision, the best thing you can do is the right thing, the next best thing is the wrong thing, and the worst thing you can do is nothing.", "Theodore Roosevelt"),
        Quote(94, "True freedom is impossible without a mind made free by discipline.", "Mortimer J. Adler"),
        Quote(95, "Act as if what you do makes a difference. It does.", "William James"),
        Quote(96, "Be not afraid of going slowly, be afraid only of standing still.", "Chinese Proverb"),
        Quote(97, "Success is stumbling from failure to failure with no loss of enthusiasm.", "Winston Churchill"),
        Quote(98, "He who has conquered his own heart is greater than one who has conquered a city.", "Proverbs 16:32"),
        Quote(99, "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus.", "Alexander Graham Bell"),
        Quote(100, "Continuous improvement is better than delayed perfection.", "Mark Twain")
    )

    fun getRandomQuote(): Quote {
        return quotes.random()
    }

    fun getQuoteByIndex(index: Int): Quote {
        val safeIndex = (index % quotes.size + quotes.size) % quotes.size
        return quotes[safeIndex]
    }
}
